apiVersion: v1
kind: Secret
metadata:
  name: rag-secret
type: Opaque
stringData:
  OPENAI_API_KEY: your-key
  QDRANT_URL: your-url
  QDRANT_API_KEY: your-qdrant-key
  COLLECTION_NAME: rag_docs
  MODEL_NAME: gpt-4o-mini